version: 2

before:
  hooks:
    - go mod tidy
project_name: git-todo
dist: artifacts/dist
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X main.version={{.Tag}}+{{.ShortCommit}}"

archives:
  - id: git-todo
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

brews:
  - name: git-todo
    repository:
      owner: kapitanov
      name: homebrew-apps
      branch: master
    commit_author:
      name: Albert Kapitanov
      email: 1442286+kapitanov@users.noreply.github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/kapitanov/git-todo
    description: A local-only list of TODO items for your git repositories
    license: MIT

nfpms:
  - id: git-todo
    package_name: git-todo
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Albert Kapitanov
    homepage: https://github.com/kapitanov/git-todo
    maintainer: Albert Kapitanov <1442286+kapitanov@users.noreply.github.com>
    description: A local-only list of TODO items for your git repositories
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
