Output demo.gif

Set FontSize 16
Set Width 1200
Set Height 600
Set WindowBar Colorful
Set BorderRadius 10

Type "git todo ls" Enter Sleep 1.5
Type "git todo add New TODO Item A" Enter Sleep 3s
Type "git todo add New TODO Item B" Enter Sleep 3s
Type "git todo check 10 11" Enter Sleep 3s
Type "git todo uncheck 10" Enter Sleep 3s
Type "git todo ls" Enter Sleep 3s
Type "git todo rm 11" Sleep 1s
Type "yes" Enter Sleep 3s
Type "git todo ls" Sleep 5s
