Output tui.webm

Set FontSize 16
Set Width 1200
Set Height 600
Set WindowBar Colorful
Set BorderRadius 10

Type "git todo" Enter Sleep 0.5
Screenshot tui.png
Sleep 2

Down@500ms Down@500ms Down@500ms Down@500ms Down@500ms Down@500ms
Space Sleep 1 Space Sleep 1
Enter Sleep 1 Type " + foo + bar" Sleep 1 Enter
Sleep 3

Type "n" Sleep 1 Type "New TODO Item" Sleep 1 Enter
Sleep 3

Type "d" Sleep 1 Type "y" Sleep 1 Enter
Sleep 3

